<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-12-03 at 06:16:08.
 */
class BillingTest extends PHPUnit_Framework_TestCase {

  /**
   * @var Billing
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $mock = $this->getMock('Billing', array('callApi'));
    $mock->method('callApi')->willReturn('foo');
    $this->object = $mock;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {

  }

  /**
   * @covers Billing::getCustomerPricing
   * @todo   Implement testGetCustomerPricing().
   */
  public function testGetCustomerPricing() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Billing::getResellerPricing
   * @todo   Implement testGetResellerPricing().
   */
  public function testGetResellerPricing() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Billing::getResellerCostPricing
   * @todo   Implement testGetResellerCostPricing().
   */
  public function testGetResellerCostPricing() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Billing::getCustomerTransactionDetails
   * @todo   Implement testGetCustomerTransactionDetails().
   */
  public function testGetCustomerTransactionDetails() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Billing::getResellerTransactionDetails
   * @todo   Implement testGetResellerTransactionDetails().
   */
  public function testGetResellerTransactionDetails() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Billing::payTransactions
   * @todo   Implement testPayTransactions().
   */
  public function testPayTransactions() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Billing::cancelInvoiceDebitNote
   * @todo   Implement testCancelInvoiceDebitNote().
   */
  public function testCancelInvoiceDebitNote() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Billing::getCustomerBalance
   * @todo   Implement testGetCustomerBalance().
   */
  public function testGetCustomerBalance() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Billing::executeOrderWithoutPayment
   * @todo   Implement testExecuteOrderWithoutPayment().
   */
  public function testExecuteOrderWithoutPayment() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Billing::searchCustomerTransaction
   * @todo   Implement testSearchCustomerTransaction().
   */
  public function testSearchCustomerTransaction() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Billing::searchResellerTransaction
   * @todo   Implement testSearchResellerTransaction().
   */
  public function testSearchResellerTransaction() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Billing::getResellerBalance
   * @todo   Implement testGetResellerBalance().
   */
  public function testGetResellerBalance() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Billing::discountInvoice
   * @todo   Implement testDiscountInvoice().
   */
  public function testDiscountInvoice() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Billing::addFundsCustomer
   * @todo   Implement testAddFundsCustomer().
   */
  public function testAddFundsCustomer() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Billing::addFundsReseller
   * @todo   Implement testAddFundsReseller().
   */
  public function testAddFundsReseller() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Billing::addDebitNoteCustomer
   * @todo   Implement testAddDebitNoteCustomer().
   */
  public function testAddDebitNoteCustomer() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Billing::addDebitNoteReseller
   * @todo   Implement testAddDebitNoteReseller().
   */
  public function testAddDebitNoteReseller() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Billing::suspendOrder
   * @todo   Implement testSuspendOrder().
   */
  public function testSuspendOrder() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Billing::unsuspendOrder
   * @todo   Implement testUnsuspendOrder().
   */
  public function testUnsuspendOrder() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Billing::getCurrentActions
   * @todo   Implement testGetCurrentActions().
   */
  public function testGetCurrentActions() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Billing::getArchiveActions
   * @todo   Implement testGetArchiveActions().
   */
  public function testGetArchiveActions() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Billing::getLegalAggrement
   * @todo   Implement testGetLegalAggrement().
   */
  public function testGetLegalAggrement() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Billing::getAllowedPaymentGatewayCustomer
   * @todo   Implement testGetAllowedPaymentGatewayCustomer().
   */
  public function testGetAllowedPaymentGatewayCustomer() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Billing::getAllowedPaymentGatewayReseller
   * @todo   Implement testGetAllowedPaymentGatewayReseller().
   */
  public function testGetAllowedPaymentGatewayReseller() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Billing::getCurrencyDetails
   * @todo   Implement testGetCurrencyDetails().
   */
  public function testGetCurrencyDetails() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Billing::getCountryList
   * @todo   Implement testGetCountryList().
   */
  public function testGetCountryList() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Billing::getStateList
   * @todo   Implement testGetStateList().
   */
  public function testGetStateList() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
        'This test has not been implemented yet.'
    );
  }

}
